### PR TITLE
Additions to OptionSetup and swap_frunk_port command

### PR DESCRIPTION
**Pull request by SylvainGa**

### CODE REVIEW

**Comment by paulobrien** [comment]
Merged, but requires further changes (i.e. not working correctly in text view and requires additional translations)

**Comment by SylvainGa** [comment]
Do you mean Swedish? Beside English and French, that's the only language I
saw there. I don't speak Swedish so I'll need to leave the translation to
someone else.

I briefly tried the text view. I'll see what has broken and correct it.
Were you able to fix the button for touch-less devices? You mention it
wasn't working two weekends ago I believe.


Le mar. 28 sept. 2021, à 14 h 35, paulobrien ***@***.***> a
écrit :

**Comment by SylvainGa** [comment]
Can you describe what's not working in text view for you? It seems to be
working OK on my Venu when set in text view. I was able to open the trunk
from the option menu, open/close the vent from the new 'select' menu and
set temperature from the option menu.

**Comment by paulobrien** [comment]
I noticed that in text mode, there's no equivalent for the 'choose
function' button you've added.

With that said, I'm not sure that change is needed. It's one click to press
the top left button then choose frunk / trunk / port, but you can do the
same by pressing the settings cog, then selecting the option from there. It
feels unnecessary, and we could just leave the direct access in settings?
Thoughts?

P

Paul O'Brien - Founder, MoDaCo Solutions

Twitter: @paulobrien <http://twitter.com/paulobrien>

**Comment by SylvainGa** [comment]
Ok, I replicated it. I'll fix and do a pull request. I will also contain
the Vents code.

Le jeu. 30 sept. 2021, à 04 h 31, paulobrien ***@***.***> a
écrit :

> I noticed that in text mode, there's no equivalent for the 'choose
> function' button you've added.
>
> With that said, I'm not sure that change is needed. It's one click to press
> the top left button then choose frunk / trunk / port, but you can do the
> same by pressing the settings cog, then selecting the option from there. It
> feels unnecessary, and we could just leave the direct access in settings?
> Thoughts?
>
> P
>
> Paul O'Brien - Founder, MoDaCo Solutions
>
> Twitter: @paulobrien <http://twitter.com/paulobrien>
>
>

**Comment by SylvainGa** [comment]
Made a pull request, it's fixed now.

**Comment by paulobrien** [comment]
Hi mate!

A quick Q - what word would you use for 'Connect' in French? I am adding a
screen for devices without glance widget support.

I'm liaising with the original dev, I think we'll do a two phase update -
an initial one then a follow up with your changes also.

P

Paul O'Brien - Founder, MoDaCo Solutions

Twitter: @paulobrien <http://twitter.com/paulobrien>

**Comment by SylvainGa** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Connect, as in connect to car, device? If that's the case, then Connexion would be the word I would use. Nice to see the app will see some love in the ConnectQ store :-)                                                                                                                                              Envoyé via Boîte de réception BlackBerry Hub+ pour Android                                                                                                                                                                           De : ***@***.***é : 25 octobre 2021 10 h 51À : ***@***.***épondre à : ***@***.*** : ***@***.***; ***@***.*** : Re: [paulobrien/garmin-tesla] Additions to OptionSetup and swap_frunk_port command (#2)  

Hi mate!



A quick Q - what word would you use for 'Connect' in French? I am adding a

screen for devices without glance widget support.



I'm liaising with the original dev, I think we'll do a two phase update -

an initial one then a follow up with your changes also.



P



Paul O'Brien - Founder, MoDaCo Solutions



Twitter: @paulobrien <http://twitter.com/paulobrien>

**Comment by paulobrien** [comment]
In the context of you open the app, and you have to press 'Connect' to
connect to the car, so yes, Connexion I think?

P

Paul O'Brien - Founder, MoDaCo Solutions

Twitter: @paulobrien <http://twitter.com/paulobrien>

**Comment by SylvainGa** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Yep, connexion is the word                                                                                                                                              Envoyé via Boîte de réception BlackBerry Hub+ pour Android                                                                                                                                                                           De : ***@***.***é : 25 octobre 2021 11 h 36À : ***@***.***épondre à : ***@***.*** : ***@***.***; ***@***.*** : Re: [paulobrien/garmin-tesla] Additions to OptionSetup and swap_frunk_port command (#2)  

In the context of you open the app, and you have to press 'Connect' to

connect to the car, so yes, Connexion I think?



P



Paul O'Brien - Founder, MoDaCo Solutions



Twitter: @paulobrien <http://twitter.com/paulobrien>

**Comment by SylvainGa** [comment]
Hi Paul,

My Venu doesn't have Glance support and didn't need that 'Touch screen to
connect' NoGlanceView to make the app work before. What was broken that
required this extra step to connect? I removed it in my repo and the App
still seems to work fine. Anything I should look for in particular?

Thanks

PS. Since my daughter and I are sharing the same 40A circuit for our Teslas
(she's moving to her own place next spring so I didn't want all the trouble
to pass another 40A circuit around the house for just a few months :-) ),
I've added a "Set Charging Amps" to the option menu to adjust the maximum
amperage drawn by the car (new feature in 2021.36).

**Comment by SylvainGa** [comment]
Hi, me again. I noticed that the climate color icon was the opposite of
what it should be. For example, ICON_BLUE was chosen when the driver SET
temperature (not current) was HIGHER than the inside temperature. I fixed
it. But more importantly. I also added two new features that are
particularly useful for us in cold climates. Under 'Options', you can now
tell the car to go into defrost mode (not just climate on) and it is
visually represented by heat waves over the fan blades icon when red. You
can also set the seats temperature to a value from 0 to 3 for either
individual seats, both front seats or rear seats, I've also implemented the
TimerRefresh routine so the icon states now follows the real state of the
car, even if you changed the setting in the app instead of the watch.

Let me know if you want me to sync the changes to your repo.

**Comment by SylvainGa** [comment]
Hi, I haven't heard back from you. Hope you're doing well.

I added a new feature that I find will be welcomed. It allows the
reordering of the Options menu so the user can set the most frequent one at
the top if he so wishes. I couldn't find a way to do it on the watch itself
so it's done in the apps setting on the phone. Since you need the app to be
published on ConnectIQ to see that option on the phone, I'm using the App
Settings in Eclipse for now. It looks like this and it regionalized:

[image: image.png]

You basically tell it how many fields you want and what that field should
show. I've taken the idea from the Crystal-face app that I'm also involved
in. Let me know what you think.

**Comment by paulobrien** [comment]
Hi mate!

Sorry for the delayed reply, things are a bit crazy at work.

Cool additions, I'll check them out.

P

**Comment by SylvainGa** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Ok cool, I'll do a pull request.                                                                                                                                             Envoyé via Boîte de réception BlackBerry Hub+ pour Android                                                                                                                                                                           De : ***@***.***é : 26 novembre 2021 13 h 13À : ***@***.***épondre à : ***@***.*** : ***@***.***; ***@***.*** : Re: [paulobrien/garmin-tesla] Additions to OptionSetup and swap_frunk_port command (#2)  

Hi mate!



Sorry for the delayed reply, things are a bit crazy at work.



Cool additions, I'll check them out.



P

**Comment by SylvainGa** [comment]
Hi Paul,

Don't know about you but I often forget I've set a precondition time until
I get a warning that the car has reached its temperature. So I added a new
visual in the Image view (not enough room in the text view unless the fonts
is made smaller) which looks like this:

[image: image.png]

So in the center of the display, if a precondition time is set, it will
display the time (otherwise it will remain blank). It's hard to miss :-)
The fan Icon also now has a new visual if the battery preheat is on so you
know that this is happening as well. So far I've modified the images.xml
for the Venu and VA 4S since they are the one my wife and I use. Let me
know if you want me to sync the changes to you. If you prefer not, that's
fine too.

**Pull request merged**
